packages:
  - docs/
  - calqula/
catalog:
  '@mdit/plugin-container': ^0.20.0
  '@types/markdown-it': ^14.1.2
  '@vitejs/plugin-vue': ^5.2.4
  '@vue/compiler-sfc': ^3.5.16
  '@vue/tsconfig': ^0.7.0
  '@vuepress/bundler-vite': 2.0.0-rc.23
  '@vuepress/client': 2.0.0-rc.23
  '@vuepress/core': 2.0.0-rc.23
  '@vuepress/helper': 2.0.0-rc.108
  '@vuepress/markdown': 2.0.0-rc.23
  '@vuepress/theme-default': 2.0.0-rc.106
  '@vuepress/utils': 2.0.0-rc.23
  '@vueuse/core': ^13.3.0
  markdown-it: ^14.1.0
  rollup: ^4.41.1
  sass: ^1.89.0
  tslib: ^2.8.1
  typescript: ^5.8.3
  vite: ^6.3.5
  vite-plugin-checker: ^0.9.3
  vue: ^3.5.16
  vue-tsc: ^2.2.10
  vuepress: 2.0.0-rc.23
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi
