packages:
  - docs/
  - calqula/
catalog:
  '@mdit/plugin-container': ^0.22.1
  '@types/markdown-it': ^14.1.2
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/compiler-sfc': ^3.5.21
  '@vue/tsconfig': ^0.8.1
  '@vuepress/bundler-vite': 2.0.0-rc.23
  '@vuepress/client': 2.0.0-rc.23
  '@vuepress/core': 2.0.0-rc.23
  '@vuepress/helper': 2.0.0-rc.108
  '@vuepress/markdown': 2.0.0-rc.23
  '@vuepress/theme-default': 2.0.0-rc.108
  '@vuepress/utils': 2.0.0-rc.23
  '@vueuse/core': ^13.9.0
  markdown-it: ^14.1.0
  rollup: ^4.50.1
  sass: ^1.92.1
  tslib: ^2.8.1
  typescript: ^5.9.2
  vite: ^7.1.5
  vite-plugin-checker: ^0.10.3
  vue: ^3.5.21
  vue-tsc: ^3.0.7-alpha.1
  vuepress: 2.0.0-rc.23
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi
